import "./globals.css";
import { SystemDataProvider } from "./context/systemDataContext";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SystemDataProvider>
    <html lang="en">
      <body>{children}</body>
    </html>
  
    </SystemDataProvider>  
  )
}
